# Generated by Django 5.1.4 on 2024-12-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcifrado',
            name='clave',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
