# Generated by Django 4.2.17 on 2025-02-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmaDocumentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivofirmado',
            name='archivo_firmado',
            field=models.FileField(blank=True, null=True, upload_to='archivos_firmados/'),
        ),
        migrations.AlterField(
            model_name='archivofirmado',
            name='archivo_original',
            field=models.FileField(upload_to='archivos_originales/'),
        ),
    ]
