# Generated by Django 4.2.17 on 2025-02-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistorialIC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("metodo", models.CharField(max_length=50)),
                ("longitud_clave", models.IntegerField()),
                ("ic", models.FloatField()),
                ("similitud", models.FloatField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
